<?php

/*
 * This file is part of the Harvest Cloud package.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace HarvestCloud\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use HarvestCloud\CoreBundle\Entity\OrderCollection;
use HarvestCloud\CoreBundle\Entity\HubWindow;
use HarvestCloud\CoreBundle\Entity\Profile;
use HarvestCloud\CoreBundle\Util\WeekView;
use HarvestCloud\CoreBundle\Util\Debug;
use HarvestCloud\CoreBundle\Util\DateTime;

/**
 * HubWindowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @author Tom Haskins-Vaughan <tom@harvestcloud.com>
 * @since  2012-10-24
 */
class HubWindowRepository extends EntityRepository
{
    /**
     * findForSelectWindowForOrderCollection()
     *
     * Find all HubWindows that have associated SellerWindows that match
     * all of the Sellers in the given OrderCollection
     *
     * @author Tom Haskins-Vaughan <tom@harvestcloud.com>
     * @since  2012-11-02
     *
     * @param  OrderCollection $orderCollection
     * @param  \DateTime       $endDate
     *
     * @return array
     */
    public function findForSelectWindowForOrderCollection(OrderCollection $orderCollection, \DateTime $endDate = null)
    {
        $em = $this->getEntityManager();

        if (null === $endDate)
        {
            $endDate = DateTime::getForEndOfWeek();
        }

        $q  = $em->createQuery('
                SELECT   hw
                FROM     HarvestCloudCoreBundle:HubWindow hw
                JOIN     hw.sellerWindows sw
                JOIN     sw.sellerHubRef  shr
                JOIN     shr.seller       s
                JOIN     hw.hub           h
                WHERE    s.id IN (:seller_ids)
                AND      UNIX_TIMESTAMP(sw.start_time) > :now
                AND      UNIX_TIMESTAMP(sw.start_time) <= :end_of_week
                GROUP BY hw.start_time, h.id
                HAVING   COUNT(sw.id) = :num_sellers
            ')
            ->setParameter('now', time())
            ->setParameter('end_of_week', $endDate->format('U'))
            ->setParameter('seller_ids', $orderCollection->getSellerIds())
            ->setParameter('num_sellers', count($orderCollection->getSellerIds()))
        ;

        $windows = $q->getResult();

        // Calculate hub fees
        foreach ($windows as $i => $window)
        {
            $window->setTotalHubFeeForOrderCollection($orderCollection);
        }

        return $windows;
    }

    /**
     * getWeekViewForOrderCollection()
     *
     * @author Tom Haskins-Vaughan <tom@harvestcloud.com>
     * @since  2013-11-07
     *
     * @return array
     */
    public function getWeekViewForOrderCollection(OrderCollection $orderCollection)
    {
        $weekView = new WeekView(new \DateTime(), null, 'D d');

        $windows = $this->findForSelectWindowForOrderCollection($orderCollection, $weekView->getEndDate());

        foreach ($windows as $window)
        {
            $weekView->addObject($window);
        }

        return $weekView;
    }

    /**
     * getCalendarViewArray()
     *
     * @author Tom Haskins-Vaughan <tom@harvestcloud.com>
     * @since  2012-10-25
     *
     * @param  HarvestCloud\CoreBundle\Entity\Profile $hub
     */
    public function getCalendarViewArray(OrderCollection $orderCollection)
    {
        $windows  = $this->findForSelectWindowForOrderCollection($orderCollection);
        $slots     = HubWindow::getSlots();

        foreach ($windows as $window)
        {
            $hour = $window->getStartTime()->format('H:i');
            $date = $window->getStartTime()->format('Y-m-d');

            if (array_key_exists($hour, $slots) && array_key_exists($date, $slots[$hour]))
            {
                $slots[$hour][$date] = $window; //->getStartTime()->format(\DateTime::ATOM);
            }
        }

        // \HarvestCloud\CoreBundle\Util\Debug::show($slots);

        return $slots;
    }

    /**
     * Find for a given Hub
     *
     * @author Tom Haskins-Vaughan <tom@harvestcloud.com>
     * @since  2013-11-19
     *
     * @param  Profile   $hub
     * @param  \DateTime $startDate
     * @param  \DateTime $endDate
     */
    public function findForHub(Profile $hub, \DateTime $startDate, \DateTime $endDate)
    {
        $em = $this->getEntityManager();

        $q  = $em->createQuery('
                SELECT w
                FROM   HarvestCloudCoreBundle:HubWindow w
                WHERE  w.hub = :hub
                AND    w.start_time >= :startDate
                AND    w.end_time   <= :endDate
            ')
            ->setParameter('hub', $hub)
            ->setParameter('startDate', $startDate)
            ->setParameter('endDate', $endDate)
        ;

        return $q->getResult();
    }

    /**
     * getWeekViewForHub()
     *
     * @author Tom Haskins-Vaughan <tom@harvestcloud.com>
     * @since  2013-11-19
     *
     * @param  Profile   $hub
     * @param  \DateTime $startDate
     * @param  \DateTime $endDate
     */
    public function getWeekViewForHub(Profile $hub, \DateTime $startDate, \DateTime $endDate = null)
    {
        if (null === $endDate)
        {
            $endDate = clone $startDate;
            $endDate->add(new \DateInterval('P6D'))->setTime(23, 59, 59);
        }

        $weekView = new WeekView($startDate, $endDate, 'D j');
        $windows  = $this->findForHub($hub, $startDate, $endDate);

        foreach ($windows as $window)
        {
            $weekView->addObject($window);
        }

        return $weekView;
    }
}
