<?php

/*
 * This file is part of the Harvest Cloud package.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace HarvestCloud\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use HarvestCloud\CoreBundle\Entity\OrderCollection;

/**
 * HubWindowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @author Tom Haskins-Vaughan <tom@harvestcloud.com>
 * @since  2012-10-24
 */
class HubWindowRepository extends EntityRepository
{
    /**
     * findForSelectWindowForOrderCollection()
     *
     * Find all HubWindows that have associated SellerWindows that match
     * all of the Sellers in the given OrderCollection
     *
     * @author Tom Haskins-Vaughan <tom@harvestcloud.com>
     * @since  2012-11-02
     *
     * @return array
     */
    public function findForSelectWindowForOrderCollection(OrderCollection $orderCollection)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->from('HarvestCloudCoreBundle:HubWindow', 'hw')
            ->select('hw')
            ->leftJoin('hw.sellerWindows', 'sw')
            ->leftJoin('sw.sellerHubRef', 'shr')
            ->leftJoin('shr.seller', 's')
            ->where($qb->expr()->in('s.id', $orderCollection->getSellerIds()))
        ;

        $q = $qb->getQuery();

        return $q->execute();
    }
}
