<?php

namespace HarvestCloud\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use HarvestCloud\CoreBundle\Entity\Location;

/**
 * LocationRepository
 *
 * @author Tom Haskins-Vaughan <tom@harvestcloud.com>
 * @since  2012-04-07
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends EntityRepository
{
    /**
     * Get a random Location from the Repository
     *
     * @author Tom Haskins-Vaughan <tom@harvestcloud.com>
     * @since  2012-04-21
     * @todo   QA this to make sure it works properly
     *
     * @return Location
     */
    public function getRandom()
    {
        $em         = $this->getEntityManager();
        $repository = $em->getRepository('HarvestCloudCoreBundle:Location');

        $query = $em->createQuery('SELECT COUNT(l.id) FROM HarvestCloud\CoreBundle\Entity\Location l');
        $count = $query->getSingleScalarResult();

        return $this->find(rand(1,$count-1));
    }
}
